<?php


namespace Happyr\ApiClient\Tests\Http;

use Happyr\ApiClient\Configuration;

use Happyr\ApiClient\Exceptions\HttpException;
use Happyr\ApiClient\Http\Client;
use Happyr\ApiClient\Http\Request\RequestInterface;
use Happyr\ApiClient\Http\Response\Response;
use Happyr\ApiClient\Http\Wsse;
use Mockery as m;

/**
 * Class ClientTest
 *
 * Test the connection class
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{
    public function testNothing()
    {
        $this->assertTrue(true);
    }
}

class DummyClient extends Client
{
    protected function handleError(Response $response)
    {
        return parent::handleError($response); // TODO: Change the autogenerated stub
    }

    protected function getAcceptHeader()
    {
        return parent::getAcceptHeader(); // TODO: Change the autogenerated stub
    }

    protected function getAuthenticationHeader()
    {
        return parent::getAuthenticationHeader(); // TODO: Change the autogenerated stub
    }
}
